import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

test("builds a self-contained offline interface", async () => {
  const [html, component, originalPdfReview, originalPdfPreview, styles, assets, sampleFiles] = await Promise.all([
    readFile(new URL("../dist/index.html", import.meta.url), "utf8"),
    readFile(new URL("../app/BundleBuilder.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/OriginalPdfReview.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/lib/original-pdf-preview.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readdir(new URL("../dist/assets/", import.meta.url)),
    readdir(new URL("../dist/guided-sample/", import.meta.url)),
  ]);

  assert.match(html, /<title>Exhibit Builder \| Offline Desktop<\/title>/i);
  assert.match(html, /rel="icon" href="\.\/favicon\.ico"/);
  const distFiles = await readdir(new URL("../dist/", import.meta.url));
  assert.ok(distFiles.includes("favicon.ico"), "Vite copies the burgundy favicon into the packaged renderer");
  assert.match(html, /Opening the offline workspace/);
  assert.match(html, /Content-Security-Policy/i);
  assert.match(html, /connect-src 'self' blob:/i);
  assert.doesNotMatch(html, /https?:\/\/|fonts\.googleapis|codex-preview/i);
  assert.ok(assets.some((name) => name.endsWith(".js")));
  assert.ok(assets.some((name) => name.endsWith(".css")));
  assert.ok(sampleFiles.includes("Witness statement"));
  assert.ok(sampleFiles.includes("Exhibits"));
  assert.ok(sampleFiles.includes("readme-images"));
  assert.deepEqual(sampleFiles.filter((name) => !["readme-images", "Witness statement", "Exhibits"].includes(name)).sort(), [
    "00_GUIDED_SAMPLE_Cover_Template.pdf",
    "00_GUIDED_SAMPLE_Index_Template.pdf",
    "06_SAMPLE_Unreferenced_Checklist.pdf",
  ]);
  const [statementFiles, exhibitFiles] = await Promise.all([
    readdir(new URL("../dist/guided-sample/Witness statement/", import.meta.url)),
    readdir(new URL("../dist/guided-sample/Exhibits/", import.meta.url)),
  ]);
  assert.deepEqual(statementFiles, ["01_GUIDED_SAMPLE_Witness_Statement.docx"]);
  assert.deepEqual(exhibitFiles.sort(), [
    "01_SAMPLE_Agreement.pdf",
    "02_SAMPLE_Invoice.pdf",
    "03_SAMPLE_Project_Report.docx",
    "04_SAMPLE_Claimant_Email.eml",
    "05_SAMPLE_Cost_Workbook.xlsx",
  ]);

  assert.match(component, /Offline desktop processing/);
  assert.match(component, /Files remain on this device/);
  assert.match(component, /does not upload or retain\s+document content/);
  assert.match(component, /run inside this desktop app/);
  assert.match(component, /Witness statement remains unchanged/);
  assert.match(component, /never writes them back into the DOCX/);
  assert.match(component, /same source file is selected for more than one statement reference/i);
  assert.match(component, /Outstanding \{pendingCandidateIds\.size\}/);
  assert.match(component, /Duplicate physical copy excluded/);
  assert.match(component, /selectedEvidenceIds\.has\(record\.id\)/);
  assert.match(component, /contextParagraphs\.map/);
  assert.match(component, /<p>\{candidate\.citation\}<\/p>/);
  assert.doesNotMatch(component, /[âÃÂ]/, "review UI source contains no mojibake sequences");
  assert.match(component, /Stage 1 of 4/);
  assert.match(component, /Cited items enter the bundle after you confirm them/);
  assert.match(component, /Unused files can be added as uncited exhibits/);
  assert.doesNotMatch(component, /A file enters the bundle only after you confirm it against a statement reference/);
  assert.match(component, /Stage 3 of 4/);
  assert.match(component, /Choose which Excel sheets to include/);
  assert.match(component, /Continue to exhibit review/);
  assert.match(component, /includedWorkbookInMatter \? "Continue to workbook sheets" : "Continue to finalise"/);
  assert.match(component, /setView\(includedWorkbookInMatter \? "sheets" : "build"\)/);
  assert.doesNotMatch(component, /setView\(includedWorkbookCount \? "sheets" : "build"\)/);
  assert.match(component, /Continue to workbook sheets/);
  assert.match(component, /Back to exhibit review/);
  assert.match(component, /data-testid="sheet-readiness"/);
  assert.match(component, /confirmed workbook/);
  assert.match(component, /cell range shown below is the part Microsoft Excel will print into A4 bundle pages/i);
  assert.match(component, /Unticked tabs stay in the source workbook but are omitted from the bundle/i);
  assert.match(component, /Include <strong>\{sheet\.name\}<\/strong> in the bundle/);
  assert.match(component, /accept="\.pdf,\.docx,\.eml,\.xlsx"/);
  assert.match(component, /Optional settings/);
  assert.match(component, /Project name, page numbering, templates and exhibit initials/);
  assert.match(component, /Exhibit initials/);
  assert.match(component, /Final suggestions will use/);
  assert.match(component, /includedReferenceMarks\.size === 1/, "the displayed reference mark comes from the one included mark");
  assert.match(component, /Apply exhibit initials/);
  assert.match(component, /does not reread or alter the witness statement/i);
  assert.match(component, /data-testid="witness-setting"/);
  assert.match(component, /Minimum number of digits/);
  assert.match(component, /Four digits gives AH-0001/);
  assert.match(component, /Page numbers shown in the PDF/);
  assert.match(component, /One sequence across the whole bundle/);
  assert.match(component, /Continue numbering across all volumes/);
  assert.match(component, /Restart numbering in each volume/);
  assert.match(component, /Page numbers will restart in every volume/);
  assert.match(component, /Volume 1 of 3/);
  assert.match(component, /Choose a template to keep its layout, or leave the standard design/);
  assert.match(component, /Prefix on every page/);
  assert.match(component, /data-testid="page-number-prefix"/);
  assert.match(component, /data-testid="page-number-suffix"/);
  assert.match(component, /Hide the guided sample from this screen/);
  assert.match(component, /Show guided sample/);
  assert.match(component, /The optional guided sample is unavailable/);
  assert.match(component, /Open the guided sample folder/);
  assert.match(component, /Run guided sample/);
  assert.match(component, /data-testid="guided-sample-tour-button"/);
  assert.match(component, /data-tour="open-folder"/);
  assert.match(component, /data-tour="choose-statement"/);
  assert.match(component, /data-tour="choose-evidence"/);
  assert.match(component, /data-tour="analyse"/);
  assert.match(component, /data-tour="confirm-all"/);
  assert.match(component, /data-tour="repeat-decision"/);
  assert.match(component, /data-tour=\{emailAttachment \? "attachments" : undefined\}/);
  assert.match(component, /data-tour="print-with-email"/);
  assert.match(component, /includedWorkbookInMatter \? "continue-sheets" : "continue-finalise"/);
  assert.match(component, /data-tour="continue-finalise"/);
  assert.match(component, /data-tour="build"/);
  assert.match(component, /data-tour="download"/);
  assert.match(component, /data-tour="save"/);
  assert.match(component, /setTourOpenedFolder\(true\)/);
  assert.match(component, /void openGuidedSampleFolder\(\)/);
  assert.match(component, /onClick=\{startGuidedSampleTour\}/);
  assert.doesNotMatch(component, /onClick=\{useSamplePack\}/);
  assert.doesNotMatch(component, /Try the guided sample/);
  assert.match(component, /exhibit-builder:analyse-guided-sample/);
  assert.match(component, /Open the guided sample folder and read the witness statement\./);
  assert.match(styles, /\.tour-current-target \{/);
  assert.match(styles, /\.guided-tour-skip \{/);
  assert.match(styles, /\.guided-tour-card-title \{/);
  assert.match(component, /aria-describedby="guided-sample-note"/);
  assert.match(component, /From placeholder to checked bundle/);
  assert.match(component, /Read one final witness statement with exhibit placeholders, reconcile every cited exhibit, and create one indexed PDF with a clear audit trail\./);
  assert.match(component, /Pick up every exhibit placeholder and keep the surrounding paragraph\./);
  assert.match(styles, /\.review-list-toolbar \{[\s\S]{0,160}justify-content:\s*flex-start/);
  assert.match(styles, /\.review-list-controls \{[\s\S]{0,220}justify-content:\s*flex-start/);
  assert.match(styles, /\.review-list-actions \{/);
  assert.match(styles, /@media \(max-width: 1050px\) \{[\s\S]{0,120}\.review-list-controls \{[\s\S]{0,80}flex-basis:\s*100%/);
  assert.doesNotMatch(styles, /\.review-list-controls \{[\s\S]{0,120}justify-items:\s*end/);
  assert.match(styles, /--text-display:\s*clamp\(44px, 5vw, 70px\)/);
  assert.match(styles, /--text-title:\s*25px/);
  assert.match(styles, /--text-body:\s*16px/);
  assert.match(styles, /--text-meta:\s*14px/);
  assert.match(styles, /\.welcome h1 \{[\s\S]{0,80}font-size:\s*var\(--text-display\)/);
  assert.match(styles, /\.welcome-lede \{[\s\S]{0,80}font-size:\s*var\(--text-body\)/);
  assert.doesNotMatch(styles, /\.welcome-lede \{[\s\S]{0,80}font-size:\s*18px/);
  assert.match(component, /Apply page-number changes/);
  assert.doesNotMatch(component, /onBlur=\{\(event\) => commitPagination\(\{ (?:prefix|suffix|padding|startAt):/);
  assert.match(component, /Turn on a page type before choosing its custom template/);
  assert.match(component, /spreadsheet\{includedWorkbookCount === 1/);
  assert.match(component, /Prefix, suffix and padding are part of the printed PDF page label/);
  assert.match(component, /paginationDraft\.startAt/);
  assert.match(component, /Change exhibit order/);
  assert.match(component, /build\.volumes \? build\.volumes\.map\(\(volume\) => <button key=\{volume\.number\} className="secondary-button"/);
  assert.match(component, /className="primary-button" type="button" onClick=\{\(\) => void downloadVolumeZip\(\)\}>Download all volumes \(\.zip\)/);
  assert.match(component, /!build\.volumes \? <button/);
  assert.match(component, /Download bundle PDF\s*<\/button> : null/);
  assert.doesNotMatch(component, /hidden=\{Boolean\(build\.volumes\)\}/);
  assert.doesNotMatch(component, /volume\.number === 1 \? "primary-button"/);
  assert.match(component, /Regenerate bundle with new arrangement/);
  assert.match(component, /warnings are not included in the exhibit bundle PDF/i);
  assert.match(component, /Choose how to include non-A4 exhibits/);
  assert.match(component, /It does not turn the page into a screenshot/);
  assert.match(component, /accept="\.pdf,\.docx"/);
  assert.match(component, /Word templates are converted locally/);
  assert.match(component, /simplified renderer/);
  assert.match(component, /Review converted PDF/);
  assert.match(component, /Review this PDF/);
  assert.match(component, /Confirm converted appearance/);
  assert.match(component, /Confirm matter details and party names/);
  assert.match(component, /These names will be printed on the finished bundle/);
  assert.match(component, /Finish from this template/);
  assert.match(component, /Use this cover as supplied/);
  assert.match(component, /Print a page number on this cover/);
  assert.match(component, /Add a volume label if the bundle is split/);
  assert.match(component, /Marks on a supplied cover stay off unless you choose them here/);
  assert.match(component, /Discard custom templates and use the built-in layout/);
  assert.match(component, /quiet-text-button/);
  assert.match(component, /\{!glued && !orderPreview && hasIndexHeadings \? <label className="move-section-control">/);
  assert.match(component, /Possible placeholders remain visible/);
  assert.match(component, /Selected templates may show different matter details/);
  assert.match(component, /openDocumentPickerId === candidate\.id \? <div className="document-picker-options"/);
  assert.match(component, /Continue to finalise/);
  assert.match(component, /Build readiness/);
  assert.match(component, /Proceed without OCR after visual review/);
  assert.match(component, /Open original PDF for visual review/);
  assert.match(component, /Open original PDF<\/button>/, "a proposed PDF can be visually checked during ordinary exhibit review");
  assert.match(component, /disabled=\{!ocrApproved && !visuallyReviewedSourceHashes\.has/);
  assert.match(component, /<OriginalPdfReview file=\{ocrSourcePreview\.file\}/);
  assert.doesNotMatch(component, /ocrSourcePreview\.url|Original PDF visual review for/, "original-source review does not depend on Chromium's blank-prone PDF iframe");
  assert.match(component, /purpose="template-preview"/);
  assert.doesNotMatch(component, /templatePreview\.url|PDF preview for \$\{templatePreview\.name\}/, "template review does not depend on Chromium's blank-prone PDF iframe");
  assert.match(originalPdfReview, /purpose === "template-preview"/);
  assert.match(styles, /\.template-preview-body \.original-pdf-review\s*\{/);
  assert.doesNotMatch(styles, /\.template-preview-body iframe/);
  assert.match(originalPdfReview, /pdfjs-dist\/legacy\/build\/pdf\.mjs/);
  assert.match(originalPdfPreview, /page\.render/);
  assert.match(originalPdfPreview, /maxCanvasPixels/);
  assert.match(originalPdfPreview, /latePage\.cleanup/);
  assert.match(originalPdfReview, /data-preview-status=\{status\}/);
  assert.match(originalPdfReview, /Preview failed/);
  assert.match(originalPdfReview, /onPageRenderedRef\.current\(\)/, "OCR approval is enabled only after a PDF page has actually rendered");
  assert.match(originalPdfReview, /Read extracted document text/);
  assert.match(originalPdfReview, /No accessible text is available/);
  assert.match(component, /ocrPreviewOrigin\.current\?\.focus\(\)/, "OCR preview restores focus to the exact opening control");
  assert.match(component, /ref=\{ocrPreviewCloseButton\}/, "OCR preview receives a predictable initial focus target");
  assert.match(component, /analysisProgressAnnouncement/, "large-matter progress uses a separate throttled live announcement");
  assert.doesNotMatch(component, /className="analysis-progress" role="status"/, "per-file visual progress is not a noisy live region");
  assert.ok(component.indexOf("{analysisProgressAnnouncement}") < component.indexOf("{!analysis ? ("), "analysis completion status persists across the welcome-to-review transition");
  assert.match(component, /<h1 ref=\{reviewHeading\} tabIndex=\{-1\}>Check the proposed exhibits<\/h1>/);
  assert.match(component, /focusReviewAfterAnalysis\.current = true/);
  assert.match(component, /Leave this Excel file out of the bundle/);
  assert.match(component, /Leave this file out of the bundle/);
  assert.match(component, /This Excel file and every exhibit that uses it are left out of the bundle/);
  assert.match(component, /The witness statement is not edited, and the file stays on your computer/);
  assert.match(component, /This file and every exhibit that uses it are left out of the bundle/);
  assert.match(component, /Every exhibit that uses it is left out too\. The witness statement is not edited/);
  assert.doesNotMatch(component, /Leave this workbook out of the bundle/);
  assert.doesNotMatch(component, /This workbook and every exhibit/);
  assert.doesNotMatch(component, /statement citation that selected this file/);
  assert.doesNotMatch(component, /statement reference that uses this workbook/);
  assert.doesNotMatch(component, /The original Excel file is not deleted/);
  assert.match(component, /className="readiness-file"/);
  assert.match(component, /workbookPlanCheckCopy/);
  assert.doesNotMatch(component, /Exclude source and its citations/);
  assert.doesNotMatch(component, /Workbook print fidelity failed/);
  assert.doesNotMatch(component, /Fidelity check failed/);
  assert.match(component, /technical exception/);
  assert.doesNotMatch(component, /review decision\{resolutions\.length === 1 \? "" : "s"\} recorded/);
  assert.doesNotMatch(component, /Show all exhibit cards/);
  assert.match(component, /showModal\(\)/);
  assert.match(component, /Start a new exhibit project\?/);
  assert.match(component, /resolution-summary/);
  assert.match(component, /finalise-readiness/);
  assert.match(component, /aria-pressed/);
  assert.match(component, /aria-current/);
  assert.match(component, /Outstanding \{pendingCandidateIds\.size\}/);
  assert.match(component, /Choose the exhibit order/);
  assert.match(component, /Earlier and Later reorder an exhibit inside its current group/);
  assert.match(component, /Add an index heading/);
  assert.match(component, /Index heading/);
  assert.match(component, /<option value="">No heading<\/option>/);
  assert.doesNotMatch(component, /No heading — still prints in the main index list/);
  assert.doesNotMatch(component, /Moving into a heading places this exhibit at the end of that heading/);
  assert.match(component, /starts at the end of the bundle/);
  assert.match(component, /Drag a heading to move that group/);
  assert.match(component, /data-action="drag-section"/);
  assert.match(component, /moveArrangementSectionBefore/);
  assert.match(component, /data-section-id=\{node\.id\}/);
  assert.match(component, /className="section-heading-row"/);
  assert.match(component, /collapsedSectionIds/);
  assert.match(component, /toggleSectionCollapsed/);
  assert.doesNotMatch(component, /<details open>/);
  assert.doesNotMatch(component, /onMouseDown=\{\(event\) => event.preventDefault\(\)\}/);
  assert.match(component, /data-action="drag-section"[\s\S]{0,180}onClick=\{\(event\) => \{ event.preventDefault\(\); event.stopPropagation\(\); \}\}/);
  assert.match(component, /heading-drop-passthrough/);
  assert.doesNotMatch(component, /unheaded-run-label">[\s\S]{0,120}data-action="drag-section"/);
  assert.match(component, /className="unheaded-run-label"/);
  assert.match(styles, /\.unheaded-run-label/);
  assert.match(component, /Earlier and Later reorder this group only/);
  assert.match(component, /this group of exhibits with no heading/);
  assert.doesNotMatch(component, /of its current section/);
  assert.match(component, /commitPaginationChange\(pagination, paginationDraft, change\)/);
  assert.match(component, /onClick=\{\(\) => commitPagination\(\{\}\)\}/);
  assert.match(component, /item\.emailAttachments \?\? \[\]\)\.find\(\(item\) => item\.identity === check\.sourceId && item\.sha256 === check\.sourceSha256\)/);
  assert.match(component, /lockPagination\(next\.pagination\)/);
  assert.match(component, /data-testid="bundle-output-summary"/);
  assert.match(component, /These pages count because the finished PDF uses one page sequence/);
  assert.match(component, /numberingDiffersFromPdfOrder\(paginationToUse\)/);
  assert.match(component, /paginationDraftAfterWarningAccept/);
  assert.match(component, /paginationDraftAfterWarningAccept\(paginationToUse, draftToUse, change\)/);
  assert.match(component, /paginationDraftAfterWarningCancel/);
  assert.match(component, /moveArrangementExhibitInContainer/);
  assert.match(component, /exhibitContainerLocation\(displayedArrangement, exhibit.exhibitId\)/);
  assert.match(component, /renderArrangementNodes/);
  assert.match(component, /hasIndexHeadings/);
  assert.match(component, /Rename heading/);
  assert.match(component, /Delete heading/);
  assert.match(component, /This heading is empty/);
  assert.match(component, /will not print in the index or appear as a PDF bookmark/);
  assert.match(component, /Jump to index heading/);
  assert.match(component, /role="status" aria-live="polite" aria-atomic="true"/);
  assert.match(component, /aria-labelledby=\{sectionHeadingDomId\(node\.id\)\}/);
  assert.match(component, /className="visually-hidden">\{node\.heading\}/);
  assert.match(component, /focusAfterArrangementChange/);
  assert.match(component, /focusAfterArrangementChange\('\[data-testid="order-preview-banner"\]'\)/);
  assert.match(component, /data-exhibit-id=\{exhibitId\}/);
  assert.match(component, /sortBundleArrangementWithinSections\(arrangement, compare\)/);
  assert.match(component, /schemaVersion: 8/);
  assert.match(component, /arrangement,/);
  assert.doesNotMatch(component, /sequenceById/, "final arrangement changes do not rewrite candidate sequence metadata");
  assert.match(component, /Preview this order/);
  assert.match(component, /Preview only/);
  assert.match(component, /Use this order/);
  assert.match(component, /Cancel preview/);
  assert.match(component, /Add exhibit/);
  assert.match(component, /Add as exhibit/);
  assert.match(component, /openManualAdd\("review"\)/);
  assert.match(component, /openManualAdd\("finalise"\)/);
  assert.match(component, /openManualAdd\("reconcile", record\.id\)/);
  assert.match(component, /Choose another local file/);
  assert.match(component, /This exhibit is not cited in the statement. No statement reference is invented. It is listed at the end of the statement reference suggestions as an uncited exhibit/);
  assert.doesNotMatch(component, /Add to bundle anyway/);
  assert.doesNotMatch(component, /not referred to in the witness statement/);
  assert.match(component, /Print with this email/);
  assert.match(component, /Add as its own exhibit/);
  assert.match(component, /data-email-attachments/);
  assert.match(component, /attachDerivedEmailEvidence/);
  assert.match(component, /filter\(\(record\) => !record\.derivedFromEmail\)/);
  assert.match(component, /added exhibit/);
  assert.match(component, /Added manually - not cited in statement/);
  assert.match(component, /Show file and build checks/);
  assert.match(component, /Optional audit details/);
  assert.match(component, /Download readable report \(\.txt\)/);
  assert.match(component, /Download technical report \(\.json\)/);
  assert.match(component, /downloadReadableBuildReport/);
  assert.match(component, /downloadTechnicalBuildReport/);
  assert.doesNotMatch(component, /Download build report/);
  assert.match(component, /selectBulkConfirmableCandidates\(candidates, exhibitGroups\)/);
  assert.match(component, /Confirm only the matches you have reviewed/);
  assert.match(component, /Statement reference format/);
  assert.match(component, /statement references confirmed/);
  assert.match(component, /Cited at paragraph/);
  assert.doesNotMatch(component, /Bundle mark \{referenceBundleMark\} \(shared; prints as/);
  assert.doesNotMatch(component, /Review list #\{itemNumber\} — index number is set in Finalise/);
  assert.match(component, /id="review-continue-status"/);
  assert.match(component, /Cannot continue — /);
  assert.doesNotMatch(component, /See other requirements/);
  assert.match(component, /"Review next requirement"/);
  assert.match(component, /nextReviewBlocker\) navigateToBlocker\(nextReviewBlocker\)/);
  assert.doesNotMatch(component, /title=\{reviewContinueReason \?\? undefined\}/);
  assert.match(component, /repeat-confirm-button/);
  assert.doesNotMatch(component, /className="repeat-confirm"/);
  assert.match(component, /await dismissRecoveryOffer\(\)/);
  assert.match(component, /async function resetWorkspace\(\) \{\s*await dismissRecoveryOffer\(\);/);
  assert.match(component, /recoverySourceDescriptors\.current = \[\];/);
  assert.match(component, /confirmation-backdrop" role="presentation"><section className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="recovery-title"/);
  assert.match(component, /data-candidate-id=\{candidate\.id\}/);
  assert.match(component, /preserveReviewViewport\(firstVisibleReviewCardId/);
  assert.match(component, /preserveNextReviewCard\(candidate\.id\)/);
  assert.match(component, /repeatNeedsDecision \? keepCurrentReviewCard\(candidate\.id\) : preserveNextReviewCard\(candidate\.id\)/);
  assert.match(component, /confirmed && repeatNeedsDecision\) keepCurrentReviewCard\(candidate\.id\)/);
  assert.match(component, /beginConfirmViewportTransaction\(candidateId\)/);
  assert.match(component, /nextPendingConfirmCardId\(cards, confirmedId\)/);
  assert.doesNotMatch(component, /function beginConfirmViewportTransaction[\s\S]{0,1200}reviewHeading/);
  assert.match(component, /data-confirm-document/);
  assert.match(component, /data-confirm-action=\{candidate\.confirmed \? "undo" : "confirm"\}/);
  assert.match(component, /data-confirmable=\{candidate\.included && candidate\.evidenceId \? "true" : "false"\}/);
  assert.match(component, /data-confirm-focus=\{!group\.selectionConflict && repeat\.id === repeatFocusId/);
  assert.match(component, /data-confirm-focus=\{group\.selectionConflict && repeat\.id === repeatFocusId/);
  assert.match(component, /if \(confirmed && attachmentsNeedDecision\) keepEmailReviewOpen\(candidate\.id\); else if \(confirmed && repeatNeedsDecision\) keepCurrentReviewCard\(candidate\.id\); else if \(confirmed\) preserveNextReviewCard\(candidate\.id\); updateCandidate\(candidate\.id,/);
  assert.match(component, /template-selected-name/);
  assert.match(component, /key=\{`\$\{slot\}-\$\{template\?\.sha256 \?\? "standard"\}`\}/);
  assert.match(component, /hidden=\{Boolean\(template\)\}/);
  assert.match(component, /input\.value = ""/);
  assert.match(styles, /\.template-control > input\[type="file"\]/);
  assert.doesNotMatch(styles, /\.template-picker input/);
  assert.match(component, /setTemplates\(\[\]\)/);
  assert.match(component, /repeatExhibitNote/);
  assert.match(component, /statement references confirmed\{repeatExhibitNote\}/);
  assert.match(component, /references confirmed\{repeatExhibitNote\}/);
  assert.match(component, /applyCandidateReviewChange/);
  assert.match(component, /candidate\.confirmed && !repeatNeedsDecision && !attachmentsNeedDecision \? <button className="secondary-button compact-action" type="button" data-confirm-focus/);
  assert.doesNotMatch(component, /const confirmationSensitive =[\s\S]{0,400}"repeatDecision"/);
  assert.match(component, /if \("repeatDecision" in change && !\("confirmed" in change\) && !\("evidenceId" in change\)\)/);
  assert.match(component, /if \(repeat\.repeatDecision !== "same"\)/);
  assert.match(component, />Minimise<\/button>/);
  assert.match(component, /document\.addEventListener\("keydown", close\)/);
  assert.match(component, /document\.addEventListener\("pointerdown", close\)/);
  assert.match(component, /restoreDocumentPickerSummary\(document\.activeElement\)/);
  assert.match(component, /restoreDocumentPickerSummary\(event\.currentTarget\)/);
  assert.match(component, /focusConfirmControl\(candidate\.id\)/);
  assert.match(component, /keepEmailReviewOpen\(parentCandidateId\)/);
  assert.match(component, /keepEmailReviewOpen\(candidateId\)/);
  assert.match(component, /if \(repeatNeedsDecision\) keepCurrentReviewCard\(candidateId\);\s*else beginConfirmViewportTransaction\(candidateId\);\s*collapseConfirmedCard\(candidateId\)/);
  assert.match(component, /emailAttachmentsSelector\(parentCandidateId\)/);
  assert.match(component, /emailAttachmentsSelector\(targetCandidateId\)/);
  assert.match(component, /probeSelectorUntilFound/);
  assert.match(component, /data-email-child-exhibit/);
  assert.match(component, /It is not printed on the bundle cover and does not affect page numbering/);
  assert.match(component, /<h3>Exhibit project name<\/h3>/);
  assert.match(component, /<h3>Page numbering<\/h3>/);
  assert.ok(component.indexOf("<h3>Exhibit project name</h3>") < component.indexOf("<h3>Page numbering</h3>"), "project name must appear before page numbering");
  assert.ok(component.indexOf("<h3>Page numbering</h3>") < component.indexOf('data-testid="page-number-prefix"'), "numbering controls remain under Page numbering");
  assert.doesNotMatch(component, /Project and page numbering/);
  assert.match(component, />View or change<\/button>/);
  assert.doesNotMatch(component, />Review<\/button>/);
  assert.match(component, /Low-confidence suggested match — check the statement wording against the selected document/);
  assert.match(component, /Low-confidence automatic suggestion/);
  assert.match(component, /<h2>Statement reference suggestions<\/h2>/);
  assert.doesNotMatch(component, /Copy-ready references for the witness statement/);
  assert.match(component, /<h3>Ready to copy<\/h3>/);
  assert.match(component, /<h3>Verify the selected source before copying<\/h3>/);
  assert.match(component, /formatStatementUpdateSuggestionText\(statementSuggestions\)/);
  assert.match(component, /copyPlainText\(statementUpdateText\)/);
  assert.match(component, /downloadBytes\(new TextEncoder\(\)\.encode\(statementUpdateText\)/);
  assert.match(component, /Copied all suggestions, including lines that need source verification before use/);
  assert.match(component, /Separate index item, kept with this email/);
  assert.match(styles, /\.email-attachment-actions button\.selected \{[\s\S]{0,80}background: var\(--green\)/);
  assert.match(styles, /#optional-settings:not\(\[open\]\) \{[\s\S]{0,80}position: sticky/);
  assert.match(styles, /#optional-settings:not\(\[open\]\) \{[\s\S]{0,120}z-index: 20/);
  assert.match(component, /confirmRepeatDecision\(repeat, !repeat\.confirmed, candidate\.id\)/);
  assert.match(component, /if \(confirmed\) keepCurrentReviewCard\(cardId\)/);
  assert.match(component, /data-confirm-focus/);
  assert.match(component, /focus\(\{ preventScroll: true \}\)/);
  assert.match(component, /if \(view !== "review"\) \{\s*confirmViewport\.current = null;\s*return;/);
  assert.doesNotMatch(component, /function confirmRepeatDecision[\s\S]{0,800}scrollIntoView/);
  assert.doesNotMatch(component, /function confirmReviewedMatches[\s\S]{0,900}scrollIntoView/);
  assert.doesNotMatch(component, /confirm-document-button[\s\S]{0,400}scrollIntoView/);
  assert.match(component, /This cover stays unnumbered unless you tick/);
  assert.match(component, /Open attachment choices on this email/);
  assert.match(component, /exhibitGroupLookupByKind\.byCandidateId\.get\(blocker\.candidateId\)\?\.canonical\.id/);
  assert.match(component, /Open paragraph \$\{unmatched.paragraph\}/);
  assert.doesNotMatch(component, /Open review list #\$\{itemNumber\}/);
  assert.match(component, /<details className="build-readiness"/);
  assert.match(component, /open=\{technicalBuildBlockers.some\(\(blocker\) => !blocker.candidateId\) \|\| undefined\}/);
  assert.match(styles, /details\.build-readiness > summary\.build-readiness-heading[\s\S]{0,80}justify-content: flex-start/);
  assert.doesNotMatch(styles, /\.build-readiness > summary::before \{[\s\S]{0,180}font-size: 11px/);
  assert.match(styles, /\.build-readiness > summary::before \{[\s\S]{0,280}width: 44px/);
  assert.match(component, /heading-drop-target/);
  assert.match(component, /headingDropTargetKey/);
  assert.match(styles, /\.arrangement-section\.heading-drop-target/);
  assert.match(component, /function beginOrderChange\(\) \{\s*if \(!build\) return;\s*setOrderChangeConfirmation\(true\);/);
  assert.doesNotMatch(component, /function beginOrderChange\(\) \{[\s\S]{0,500}window\.confirm/);
  assert.match(component, /order-change-confirmation-title/);
  assert.match(component, /function confirmOrderChange\(\)/);
  assert.match(component, /readiness-jump-list/);
  assert.match(component, /will be used throughout this bundle and in the final suggestions/);
  assert.match(component, /Reference marks need review/);
  assert.match(component, /Choose one statement-reference mark in Optional settings before continuing/);
  assert.match(component, /Use \{initialsConfirmation\.proposed\} throughout this bundle/);
  assert.match(component, /Confirm this document/);
  assert.match(component, /Undo confirmation/);
  assert.match(component, /repeatDecision: "pending", confirmed: false/);
  assert.match(component, /className="document-picker"/);
  assert.match(component, /className="document-picker-options" role="group"/);
  assert.match(component, /open=\{openDocumentPickerId === candidate\.id\}/);
  assert.match(component, /onToggle=\{\(event\) => \{ if \(event\.currentTarget\.open\)/);
  assert.match(component, /reviewItemNumbers\(reviewCandidates\)/);
  assert.match(component, /reviewCandidatesForDisplay\(candidates, exhibitGroups\)/);
  assert.match(component, /role="group" aria-label=\{`Available documents for review list/);
  assert.doesNotMatch(component, /className="document-picker-options" role="listbox"/);
  assert.doesNotMatch(component, /role="option"/);
  assert.match(component, /aria-pressed=\{selected\}/);
  assert.match(component, /confirmationDialogKey/);
  assert.match(component, /\[view, workspaceAvailable\]/);
  assert.match(component, /exhibitGroupLookup\(exhibitGroups\)/, "review candidates and final-order nodes use explicit identity-scoped lookups");
  assert.match(component, /byCandidateId\.get\(candidate\.id\)/);
  assert.match(component, /byGroupId\.get\(exhibitId\)/);
  assert.match(component, /aria-pressed=\{repeat\.repeatDecision === "same"\}/);
  assert.match(component, /repeat-resolved-\$\{group\.id\}/);
  assert.match(component, /Repeat decision needed/);
  assert.match(component, /Confirm how the repeated reference should be treated/);
  assert.match(component, /compact = candidate\.confirmed/);
  assert.match(component, /Review supporting details/);
  assert.match(component, /className="review-index-fields"/);
  assert.match(component, /Document date for \$\{candidate\.mark\}/);
  assert.doesNotMatch(component, /Document date: \{candidate\.date\}/);
  assert.doesNotMatch(component, /supporting-review-details[\s\S]*description-input/);
  assert.match(component, /workspace-header-actions[\s\S]*build-progress/);
  assert.match(component, /build-progress-stage/);
  assert.match(component, /aria-live="polite"/);
  assert.match(component, /copy-feedback[\s\S]*role="status"/);
  assert.match(component, /bundleBuilderDesktop\?\.copyText/);
  assert.match(component, /Copy failed\. Download the \.txt file instead/);
  assert.match(component, /Include selected pages only/);
  assert.match(component, /Strong suggested match/);
  assert.match(component, /comparison score: \{candidate\.confidence\}\/100/);
  assert.match(component, /not the probability that the document is correct/);
  assert.match(component, /I have reviewed the proposed document for each listed exhibit/);
  assert.match(component, /Local recovery data/);
  assert.match(component, /review-sticky-bar/);
  assert.doesNotMatch(component, /exhibit-mark-summary/);
  assert.doesNotMatch(component, /className="mark-badge"/);
  assert.doesNotMatch(component, /key=\{record\.mark\}/);
  assert.doesNotMatch(component, /Human-confirmed/);
  assert.match(component, /moveCandidateBefore/);
  assert.doesNotMatch(component, /<label>Profile<select/);
  assert.match(styles, /body\s*\{[\s\S]*font-size:\s*16px/);
  assert.match(styles, /\.readiness-item strong\s*\{[\s\S]*font-size:\s*var\(--text-body\)/);
  assert.match(styles, /\.readiness-detail\s*\{[\s\S]*font-size:\s*var\(--text-meta\)/);
  assert.match(styles, /\.readiness-file\s*\{[\s\S]*font-size:\s*var\(--text-meta\)/);
  assert.match(styles, /\.readiness-file\s*\{[\s\S]*font-weight:\s*650/);
  assert.match(styles, /\.readiness-action-note\s*\{[\s\S]*font-size:\s*var\(--text-meta\)/);
  assert.match(styles, /\.resolution-summary\s*\{/);
  assert.match(styles, /\.section-heading-row\s*\{/);
  assert.match(styles, /\.readiness-jump-list/);
  assert.match(styles, /\.heading-drop-passthrough/);
  assert.match(styles, /\.resolution-summary h2 \{[\s\S]{0,120}color:\s*var\(--ink\)/);
  assert.doesNotMatch(styles, /\.arrangement-section summary\s*\{/);
  assert.match(styles, /\.review-progress-strip\s*\{/);
  assert.match(styles, /\.review-index-fields \.description-input \{[^}]*font-size:\s*14px/);
  assert.match(styles, /\.exhibit-card-grid select, \.exhibit-card-grid \.description-input \{[^}]*font-size:\s*14px/);
  assert.match(styles, /\.document-picker \{[^}]*font-size:\s*14px/);
  assert.match(styles, /\.citation-preview > strong \{[^}]*font-size:\s*var\(--text-body\)/);
  assert.match(styles, /\.confirm-document-button \{[^}]*min-height:\s*44px/);
  assert.match(styles, /\.supporting-review-details > summary \{[^}]*min-height:\s*44px/);
  assert.match(styles, /\.supporting-review-details > summary::before \{[\s\S]{0,280}width: 44px/);
  assert.match(styles, /\.supporting-review-details\[open\] > summary::before \{[^}]*content:\s*"▾"/);
  assert.doesNotMatch(styles, /\.document-picker > summary::before/);
  assert.match(styles, /\.manual-exhibit-note\s*\{/);
  assert.doesNotMatch(styles, /\.manual-exhibit-warning\s*\{/);
  assert.match(styles, /\.copy-feedback\.is-failure\s*\{/);
  assert.match(styles, /\.document-picker\s*\{/);
  assert.match(styles, /\.document-picker-options\s*\{/);
  assert.match(styles, /\.review-sticky-bar\s*\{/);
  assert.match(styles, /\.arrangement-section\s*\{/);
  assert.match(styles, /\.move-section-control\s*\{/);
  assert.match(styles, /\.template-grid \.cover-insertion > label[\s\S]*flex-direction:\s*row/);
  assert.match(styles, /\.template-grid input:not\(\[type="radio"\]\):not\(\[type="checkbox"\]\) \{[^}]*background:[^}]*padding:[^}]*width:\s*100%/);
  assert.match(styles, /\.cover-insertion > label input \{[^}]*background:\s*none;[^}]*border:\s*0;[^}]*width:\s*auto/);
  assert.match(styles, /\.cover-insertion span \{[^}]*min-width:\s*0/);
  assert.match(styles, /\.primary-template-grid \{[^}]*grid-template-columns:\s*1fr/);
  assert.doesNotMatch(styles, /\.primary-template-grid:has\(/);
  assert.doesNotMatch(styles, /\.move-section-control select \{[^}]*max-width:\s*210px/);
  assert.doesNotMatch(styles, /\.template-grid input \{/);
  assert.match(styles, /\.quiet-text-button\s*\{/);
  assert.match(styles, /\.built-in-matter\s*\{/);
  assert.match(styles, /\.section-add-control\s*\{/);
  assert.match(styles, /\.section-jump-control\s*\{/);
  assert.match(styles, /@media \(pointer: coarse\)/);
  assert.match(styles, /min-block-size:\s*44px/);
  assert.match(styles, /\.finalise-order-item b, \.finalise-order-item small \{[^}]*overflow-wrap:\s*anywhere;[^}]*white-space:\s*normal;/);
  assert.match(styles, /\.order-toolbar select,[\s\S]*?\.order-toolbar button \{\s*min-height:\s*44px;/);
  assert.match(styles, /@media \(prefers-reduced-motion:\s*reduce\)/);
  assert.match(styles, /\.build-progress-spinner \{\s*animation:\s*none;/);
  assert.doesNotMatch(styles, /\.exhibit-mark-summary\s*\{/);
  assert.match(styles, /button:focus-visible/);
  assert.match(styles, /scroll-padding-top:\s*80px/);
  assert.match(styles, /\.exhibit-review-card:focus/);
  assert.match(styles, /\.email-attachments-panel:focus/);
  assert.match(component, /emailChildInsertAfter\(rawExhibitGroups\)/);
  assert.match(component, /probeUntilStable/);
  assert.match(component, /firstActionableControl/);
  assert.match(component, /emailChildDescriptionSelector\(manualCandidate\.id\)/);
  assert.match(component, /blocker\.code\?\.startsWith\("email\.attachment_"\)/);
  assert.match(component, /setShowDuplicatesOnly\(false\);\s*if \(emailAttachment\) setShowPendingOnly\(false\)/);
  assert.match(component, /updateManualCandidate\(childExhibit\.id, \{ pageStart/);
  assert.doesNotMatch(component, /updateCandidate\(childExhibit\.id, \{ pageStart/);
  assert.match(component, /if \(evidence\.derivedFromEmail\) continue/);
  assert.match(component, /reviewContinueReason \? ` — \$\{reviewContinueReason\}`/);
  assert.match(component, /keepEmailReviewOpen\(candidate\.id\)/);
  assert.match(component, /pendingCandidateIds\.size === 0/);
  assert.match(component, /role="group" aria-label=\{`Index details for \$\{child\.name\}`\}/);
  assert.doesNotMatch(component, /details className="build-readiness" aria-live/);
  assert.match(component, /emailChildrenForDisposition\(record\.emailAttachments, group\.canonical\.emailAttachmentDispositions, "print-with-email"\)/);
  assert.match(originalPdfReview, /role="toolbar"/);
  assert.match(originalPdfReview, /role="img"/);
  assert.match(originalPdfReview, /role="region"/);
  assert.match(originalPdfReview, /documentRef\.current = openedDocument/);
});
